apiVersion: v1
kind: Service
metadata:
  name: nexus-backend-service
spec:
  selector:
    app: nexus-backend
    slot: blue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
