apiVersion: v1
kind: ConfigMap
metadata:
  name: test-statistics-config
  namespace: test
data:
  SPRING_PROFILES_ACTIVE: prod
  DB_URL: jdbc:mariadb://test-statistics-db-service:3306/nexus
  DB_DRIVER: org.mariadb.jdbc.Driver
  DB_USER: root
  KAFKA_BOOTSTRAP_SERVERS: nexus-kafka-kafka-bootstrap.kafka.svc:9092
  KAFKA_GROUP_ID: test-statistics-prod
  SQL_INIT_MODE: never
  REDIS_HOST: "test-redis-service"