
server:
  port: 8088

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10     # 주소를 갱신하는 시간
    lease-expiration-duration-in-seconds: 30  # 가져온 주소의 만료 시간
    prefer-ip-address: true                   # 내 주소를 알려줄 때 Hostname 대신 IP 주소 알려주기
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
    register-with-eureka: false
    fetch-registry: true

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: statistics
          uri: lb://NexusStatistics
          predicates:
            - Path=/statistics/**
          filters:
            - Jwt

        - id: pos
          uri: lb://NexusPos
          predicates:
            - Path=/pos/**
          filters:
            - Jwt





