spring:
  application:
    name: gateway



  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: statistics
              uri: http://localhost:8081
              predicates:
                - Path=/statistics/**
              filters:
                - JwtFilter
            - id: pos
              uri: http://localhost:8082
              predicates:
                - Path=/pos/**
              filters:
                - JwtFilter


            - id: origin
              uri: http://localhost:8080
              predicates:
                - Path=/**



server:
  port: 8088