apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-frontend-blue
  labels:
    app: nexus-frontend
    slot: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-frontend
      slot: blue
  template:
    metadata:
      labels:
        app: nexus-frontend
        slot: blue
    spec:
      containers:
        - name: nexus-frontend
          image: deatytim/nexusfront:latest
          ports:
            - containerPort: 80
