apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-frontend-{{COLOR}}
  namespace: default
  labels:
    app: nexus-frontend
    color: {{COLOR}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-frontend
      color: {{COLOR}}
  template:
    metadata:
      labels:
        app: nexus-frontend
        color: {{COLOR}}
    spec:
      containers:
        - name: nexus-frontend
          image: deatytim/nexus-frontend:{{IMAGE_TAG}}
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
