spring:
  application:
    name: Nexus
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 0.3

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        store-bucket: ${AWS_S3_STORE_BUCKET}
        menu-bucket: ${AWS_S3_MENU_BUCKET}
      region:
        static: ${AWS_S3_STATIC}
  sql:
    init:
      mode: always

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
