spring:
  application:
    name: Nexus
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  sql:
    init:
      mode: always

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
